### ISSUE TITLE
sort function bug

### ISSUE THREAD

**Issue by chenkovsky** [google/cayley#224]
[1,-1].sort(function(a,b){return a -b;});
in cayley, it returns [1,-1]
but it should be [-1,1]

**Comment by barakmich** [comment]
This appears to be an upstream bug with http://github.com/robertkrimen/otto:

From latest:
```
$ ./otto
a = [1,-1].sort(function(a,b){return a -b;});
console.log(a)
1,-1
```

Good catch! Unfortunately, I can't help but to repro. Please file the same bug against the otto repository?
