### ISSUE TITLE
Add Predicate/Edge Type functionality to query language

### ISSUE THREAD

**Issue by theRanalyst** [google/cayley#239]
There should be a way to query the graph to return all predicates/edge types so that we know what can be used in the In( ) and Out( ) commands. For example, if the 30kmoviedata.nq.gz data, it would be nice to know if something like g.V( ).Out("director").All( ) would fail or not without having to go through trial and error. Ideally, something like g.predicates( ).All( ) would return a list of the nodes in the graph with a "relationship" type. 

The predicate function should allow the use of both .All( ) and .GetLimit( ) so the user can limit the number of values returned if needed.

**Comment by kortschak** [comment]
Can you explain how this would work? Predicates are part of each quad, so all legal stored quads have predicates.

**Comment by kortschak** [comment]
Ah, OK, having seen @allonhadaya's PR now that makes sense. I was replying to "Ideally, something like g.predicates( ).All( ) would return a list of the nodes in the graph with a "relationship" type." which reads ambiguously to me.

**Comment by bbritten** [comment]
Yeah, sorry, I didn't mean to be so vague with the language. I was trying to describe it as accurately as possible without knowing too much about it.
