### ISSUE TITLE
how to exit repl console

### ISSUE THREAD

**Issue by rrphotosoft** [google/cayley#261]
Hi,
Just got started with cayley. How do I quit the repl console? Is there a --help command somewhere that enumerates all available commands in the console?? Could this be added to the docs.
Thanks,
Rr.

**Comment by tmlbl** [comment]
I had the same confusion. I modified mine to quit the repl when the user types `exit`

**Comment by mohan-chinnappan-n** [comment]
^D (control + D) will do the quit
