### ISSUE TITLE
Mongodb Use Too many hd and Load very slow

### ISSUE THREAD

**Issue by benben-yunyun** [google/cayley#276]
cayley with single mongdb:
100M data use 3G HD to store in mongodb and use 20 minutes.
700M data use 20G HD to store in mongodb and not finished in 2 hours. 

I want to store 500G data about 1.5 Billion edges, can cayley handle data scale?

If OK, how many mongodbs to store the data?

**Comment by barakmich** [comment]
Not enough data for a meaningful answer

So, Mongo is relatively slow, in general; it's a remote backend. Decent for large graphs (and if you want to shard things) but it's going to be slow to load and query, and may take up a lot of space. The idea being if you want something that big that shards, you're willing to pay the cost.

Setting up a sharded Mongo will likely be a plus, at least with regard to disk usage. I'm not sure what your infrastructure requirements are.
