### ISSUE TITLE
What are the labels in Cayley

### ISSUE THREAD

**Issue by isikfsc** [google/cayley#363]
What are the labels in Cayley, I see they are introduced but not yet in docs.
What are the usage of them, and where do label concept fit in graph?

**Comment by dennwc** [comment]
Please check [this answer](https://groups.google.com/forum/?hl=en#!searchin/cayley-users/label/cayley-users/sDZIYaIFZEY/6yOEewsPlbAJ). I think it covers your questions.

**Comment by isikfsc** [comment]
yes, thanks.
