### ISSUE TITLE
Outdate README and Dockerfile

### ISSUE THREAD

**Issue by MartinBrugnara** [google/cayley#384]
- Default `HTTP port` is `64210` not `64321`.
  - change docker file to expose `64210` instead. 
  - update example

- At `quay.io/barakmich/cayley`  there is nothing.  
Replace example with:
```bash
$ git clone https://github.com/google/cayley
$ cd cayley
$ docker build -t google/caylay
$ docker run --rm -v $(PWD)/data:data -p 64210:64210 google/cayley
```

**Comment by mayankasthana** [comment]
This seems to same as #357.

**Comment by MartinBrugnara** [comment]
Close ref: #357 #367
