### ISSUE TITLE
How to update (change) the object of an existing quad

### ISSUE THREAD

**Issue by yaa110** [google/cayley#392]
I've used the following example:

```go
import (
	"fmt"
	_ "github.com/google/cayley/graph/bolt"
	"github.com/google/cayley/graph"
	"github.com/google/cayley"
)

func main() {
	path := "test.bolt.db"

	graph.InitQuadStore("bolt", path, nil)

	store, err := cayley.NewGraph("bolt", path, nil)
	if err != nil {
		fmt.Println(err)
	}

	store.AddQuad(cayley.Quad("food", "is", "good", ""))

	p := cayley.StartPath(store, "food").Out("is")

	it := p.BuildIterator()
	for cayley.RawNext(it) {
		fmt.Println(store.NameOf(it.Result()))
	}
}
```

How can I update an existing quad? e.g. how can I change `good` to `delicious`? 
_Do I have to delete the the existing quad, then add a new quad?_

**Comment by dennwc** [comment]
Hi @yaa110,

In most of backend implementations quads are identified by content, thus there is no way to update quad. You may need to remove old quad and insert a new one it in transaction instead. This may change, but for now you should use transactions (deltas) for this.

**Comment by yaa110** [comment]
Thank you @dennwc, do you have any code example of using Deltas?

**Comment by dennwc** [comment]
Check docs for [Transaction](https://godoc.org/github.com/google/cayley/graph#Transaction).
For your example this should work:
```Go
tx := graph.NewTransaction()
tx.RemoveQuad(cayley.Quad("food", "is", "good", ""))
tx.AddQuad(cayley.Quad("food", "is", "delicious", ""))

err := store.ApplyTransaction(tx)
```
