### ISSUE TITLE
How to get quads sorted by their predicate

### ISSUE THREAD

**Issue by yaa110** [google/cayley#393]
Consider following quads:
```
"A" "age" "25" ""
"B" "age" "15" ""
"C" "age" "50" ""
"D" "age" "40" ""
```
How could I iterate over these quads sorted by `age` (Embedded API)?

**Comment by dennwc** [comment]
@yaa110 There is no support for sorting right now. I think all backends supports this, but it's not implemented in the Cayley API. The only way for now is to do sort client-side, which is not so great, I assume.
